# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_games',
            name='purchase_time',
        ),
    ]
