# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0002_remove_purchased_games_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_games',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
