# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0003_purchased_games_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
