# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0004_auto_20180213_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='type_of_user',
            new_name='developer',
        ),
    ]
