# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0006_auto_20180213_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_list',
            name='image',
            field=models.ImageField(default='https://docs.djangoproject.com/s/img/small-fundraising-heart.d255f6e934e5.png', upload_to='game_images/'),
            preserve_default=False,
        ),
    ]
