# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0007_game_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_list',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
