# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0009_auto_20180228_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_list',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
