# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0010_game_list_time_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_List',
            new_name='GameList',
        ),
        migrations.RenameModel(
            old_name='Purchased_Games',
            new_name='PurchasedGames',
        ),
        migrations.RenameModel(
            old_name='User_Type',
            new_name='UserType',
        ),
    ]
