# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0011_auto_20180228_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedgames',
            old_name='g',
            new_name='game',
        ),
    ]
