# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0012_auto_20180302_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='description',
            field=models.TextField(),
        ),
    ]
