# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0013_auto_20180302_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
